/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "video/connect_options.h"
/* Header for class com_twilio_video_ConnectOptions */

#ifndef _Included_com_twilio_video_ConnectOptions
#define _Included_com_twilio_video_ConnectOptions
#ifdef __cplusplus
extern "C" {
#endif


struct ConnectOptionsDataContext {
  ConnectOptionsDataContext() :
      connect_options(twilio::video::ConnectOptions::Builder().build()){ }
  twilio::video::ConnectOptions connect_options;
};

JNIEXPORT jlong JNICALL Java_com_twilio_video_ConnectOptions_nativeCreate
    (JNIEnv *, jobject, jstring, jboolean, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
