/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twilio_conversations_impl_TwilioConversationsImpl */

#ifndef _Included_com_twilio_conversations_impl_TwilioConversationsImpl
#define _Included_com_twilio_conversations_impl_TwilioConversationsImpl
#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT jlong JNICALL Java_com_twilio_conversations_impl_ConversationsImpl_createEndpoint
  (JNIEnv *, jobject, jobject, jobjectArray, jlong);




#ifdef __cplusplus
}
#endif
#endif
