/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twilio_conversations_impl_CameraCapturerImpl */

#ifndef _Included_com_twilio_conversations_impl_CameraCapturerImpl
#define _Included_com_twilio_conversations_impl_CameraCapturerImpl
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_twilio_conversations_impl_CameraCapturerImpl_stopVideoSource
  (JNIEnv *, jobject, jlong);

JNIEXPORT void JNICALL Java_com_twilio_conversations_impl_CameraCapturerImpl_restartVideoSource
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
