/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twilio_conversations_impl_ConversationsClientImpl */

#ifndef _Included_com_twilio_conversations_impl_ConversationsClientImpl
#define _Included_com_twilio_conversations_impl_ConversationsClientImpl
#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT jlong JNICALL
Java_com_twilio_conversations_impl_TwilioConversationsClientImpl_createEndpoint
  (JNIEnv *, jobject, jobject, jobjectArray, jlong);

/*
 * Class:     com_twilio_conversations_impl_ConversationsClientImpl
 * Method:    listen
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_twilio_conversations_impl_TwilioConversationsClientImpl_listen__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_twilio_conversations_impl_ConversationsClientImpl
 * Method:    unlisten
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_twilio_conversations_impl_TwilioConversationsClientImpl_unlisten__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_twilio_conversations_impl_ConversationsClientImpl
 * Method:    reject
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_twilio_conversations_impl_TwilioConversationsClientImpl_reject__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_twilio_conversations_impl_ConversationsClientImpl
 * Method:    freeNativeHandle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_twilio_conversations_impl_TwilioConversationsClientImpl_freeNativeHandle
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
