/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twilio_conversations_impl_ConversationImpl */

#ifndef _Included_com_twilio_conversations_impl_ConversationImpl
#define _Included_com_twilio_conversations_impl_ConversationImpl

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_com_twilio_conversations_impl_ConversationImpl_nativeWrapOutgoingSession
  (JNIEnv *, jobject, jlong, jlong, jobjectArray);

JNIEXPORT void JNICALL Java_com_twilio_conversations_impl_ConversationImpl_nativeStart
  (JNIEnv *, jobject, jlong, jboolean, jboolean, jboolean, jboolean, jobject, jobjectArray, jobject);

JNIEXPORT void JNICALL Java_com_twilio_conversations_impl_ConversationImpl_nativeStop
  (JNIEnv *, jobject, jlong);

JNIEXPORT void JNICALL Java_com_twilio_conversations_impl_ConversationImpl_nativeSetExternalCapturer
  (JNIEnv *, jobject, jlong, jlong);

JNIEXPORT void JNICALL Java_com_twilio_conversations_impl_ConversationImpl_nativeSetSessionObserver
  (JNIEnv *, jobject, jlong, jlong);

JNIEXPORT void JNICALL Java_com_twilio_conversations_impl_ConversationImpl_nativeFreeHandle
  (JNIEnv *, jobject, jlong);

JNIEXPORT jboolean JNICALL Java_com_twilio_conversations_impl_ConversationImpl_nativeEnableVideo
  (JNIEnv *, jobject, jlong, jboolean, jboolean, jobject);

JNIEXPORT jboolean JNICALL Java_com_twilio_conversations_impl_ConversationImpl_nativeMute
  (JNIEnv *, jobject, jlong, jboolean);

JNIEXPORT jboolean JNICALL Java_com_twilio_conversations_impl_ConversationImpl_nativeIsMuted
  (JNIEnv *, jobject, jlong);

JNIEXPORT void JNICALL Java_com_twilio_conversations_impl_ConversationImpl_nativeInviteParticipants
  (JNIEnv *, jobject, jlong, jobjectArray);

JNIEXPORT jstring JNICALL Java_com_twilio_conversations_impl_ConversationImpl_nativeGetConversationSid
  (JNIEnv *, jobject, jlong);

JNIEXPORT jboolean JNICALL Java_com_twilio_conversations_impl_ConversationImpl_nativeEnableAudio
  (JNIEnv *, jobject, jlong, jboolean, jboolean);


#ifdef __cplusplus
}
#endif
#endif
