/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twilio_conversations_impl_CameraCapturerImpl */

#ifndef _Included_com_twilio_conversations_impl_CameraCapturerImpl
#define _Included_com_twilio_conversations_impl_CameraCapturerImpl
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_twilio_conversations_impl_CameraCapturerImpl_nativeStopVideoSource
        (JNIEnv *, jobject, jlong);

JNIEXPORT void JNICALL Java_com_twilio_conversations_impl_CameraCapturerImpl_nativeRestartVideoSource
        (JNIEnv *, jobject, jlong);

JNIEXPORT jlong JNICALL
Java_com_twilio_conversations_impl_CameraCapturerImpl_nativeCreateNativeCapturer(JNIEnv *env,
                                                                                 jobject instance,
                                                                                 jobject j_video_capturer);

JNIEXPORT void JNICALL
Java_com_twilio_conversations_impl_CameraCapturerImpl_nativeDisposeCapturer(JNIEnv *env,
                                                                            jobject instance,
                                                                            jlong nativeVideoCapturerAndroid);

#ifdef __cplusplus
}
#endif
#endif
