/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <media/ice_options.h>
/* Header for class com_twilio_video_IceOptions */

#ifndef _Included_com_twilio_video_IceOptions
#define _Included_com_twilio_video_IceOptions
#ifdef __cplusplus
extern "C" {
#endif

struct IceOptionsContext {
    twilio::media::IceOptions ice_options;
};

JNIEXPORT jlong JNICALL Java_com_twilio_video_IceOptions_nativeCreate
  (JNIEnv *, jobject, jobjectArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
