/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twilio_signal_impl_VideoSurface */

#ifndef _Included_com_twilio_signal_impl_VideoSurface
#define _Included_com_twilio_signal_impl_VideoSurface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_twilio_signal_impl_VideoSurface
 * Method:    freeVideoSurface
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_twilio_signal_impl_VideoSurface_freeVideoSurface
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_twilio_signal_impl_VideoSurface
 * Method:    freeObserver
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_twilio_signal_impl_VideoSurface_freeObserver
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
