/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twilio_signal_impl_VideoSurfaceFactory */

#ifndef _Included_com_twilio_signal_impl_VideoSurfaceFactory
#define _Included_com_twilio_signal_impl_VideoSurfaceFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_twilio_signal_impl_VideoSurfaceFactory
 * Method:    nativeCreateVideoSurfaceObserver
 * Signature: (Lcom/twilio/signal/impl/VideoSurfaceObserver;)J
 */
JNIEXPORT jlong JNICALL Java_com_twilio_signal_impl_VideoSurfaceFactory_nativeCreateVideoSurfaceObserver
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_twilio_signal_impl_VideoSurfaceFactory
 * Method:    nativeCreateVideoSurface
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_twilio_signal_impl_VideoSurfaceFactory_nativeCreateVideoSurface
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
