/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twilio_signal_impl_VideoTrackImpl */

#ifndef _Included_com_twilio_signal_impl_VideoTrackImpl
#define _Included_com_twilio_signal_impl_VideoTrackImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_twilio_signal_impl_VideoTrackImpl
 * Method:    nativeWrapVideoRenderer 
 * Signature: (J)V
 */
JNIEXPORT jobject JNICALL Java_com_twilio_signal_impl_VideoTrackImpl_nativeWrapVideoRenderer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
