/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twilio_signal_impl_VideoSurface_Observer */

#ifndef _Included_com_twilio_signal_impl_VideoSurface_Observer
#define _Included_com_twilio_signal_impl_VideoSurface_Observer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
