/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twilio_signal_impl_ConversationImpl */

#ifndef _Included_com_twilio_signal_impl_ConversationImpl
#define _Included_com_twilio_signal_impl_ConversationImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_twilio_signal_impl_ConversationImpl
 * Method:    wrapOutgoingSession
 * Signature: (JJ[Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_twilio_signal_impl_ConversationImpl_wrapOutgoingSession
  (JNIEnv *, jobject, jlong, jlong, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
