/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twilio_signal_impl_TwilioRTCImpl */

#ifndef _Included_com_twilio_signal_impl_TwilioRTCImpl
#define _Included_com_twilio_signal_impl_TwilioRTCImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_twilio_signal_impl_TwilioRTCImpl
 * Method:    initCore
 * Signature: (Landroid/content/Context;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_twilio_signal_impl_TwilioRTCImpl_initCore
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_twilio_signal_impl_TwilioRTCImpl
 * Method:    createEndpoint
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_twilio_signal_impl_TwilioRTCImpl_createEndpoint
  (JNIEnv *, jobject, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
