/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twilio_signal_impl_TwilioCore */

#ifndef _Included_com_twilio_signal_impl_TwilioCore
#define _Included_com_twilio_signal_impl_TwilioCore


#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_twilio_signal_impl_TwilioCore
 * Method:    initCore
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_twilio_signal_impl_SignalCore_initCore
  (JNIEnv *, jobject);

/*
 * Class:     com_twilio_signal_impl_TwilioCore
 * Method:    isCoreInitialized
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_twilio_signal_impl_SignalCore_isCoreInitialized
  (JNIEnv *, jobject);

/*
 * Class:     com_twilio_signal_impl_TwilioCore
 * Method:    login
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_twilio_signal_impl_SignalCore_login
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
