/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twilio_signal_impl_EndpointListenerInternal */

#ifndef _Included_com_twilio_signal_impl_EndpointListenerInternal
#define _Included_com_twilio_signal_impl_EndpointListenerInternal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_twilio_signal_impl_EndpointListenerInternal
 * Method:    wrapNativeObserver
 * Signature: (Lcom/twilio/signal/EndpointListener;)J
 */
JNIEXPORT jlong JNICALL Java_com_twilio_signal_impl_EndpointListenerInternal_wrapNativeObserver
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_twilio_signal_impl_EndpointListenerInternal
 * Method:    freeNativeObserver
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_twilio_signal_impl_EndpointListenerInternal_freeNativeObserver
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
