/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twilio_signal_impl_ConversationImpl_SessionObserverInternal */

#ifndef _Included_com_twilio_signal_impl_ConversationImpl_SessionObserverInternal
#define _Included_com_twilio_signal_impl_ConversationImpl_SessionObserverInternal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_twilio_signal_impl_ConversationImpl_SessionObserverInternal
 * Method:    wrapNativeObserver
 * Signature: (Lcom/twilio/signal/ConversationListener;Lcom/twilio/signal/Endpoint;)J
 */
JNIEXPORT jlong JNICALL Java_com_twilio_signal_impl_ConversationImpl_00024SessionObserverInternal_wrapNativeObserver
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_twilio_signal_impl_ConversationImpl_SessionObserverInternal
 * Method:    freeNativeObserver
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_twilio_signal_impl_ConversationImpl_00024SessionObserverInternal_freeNativeObserver
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
