/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twilio_signal_impl_EndpointImpl */

#ifndef _Included_com_twilio_signal_impl_EndpointImpl
#define _Included_com_twilio_signal_impl_EndpointImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_twilio_signal_impl_EndpointImpl
 * Method:    listen
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_twilio_signal_impl_EndpointImpl_listen
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
